#!/usr/bin/env python3
"""
Create a new database migration using Alembic
"""

import subprocess
import sys
import os
from pathlib import Path
import re

# Add backend directory to Python path
backend_dir = Path(__file__).parent.parent
sys.path.insert(0, str(backend_dir))

def create_migration(message):
    """Create a new migration with the given message"""
    print(f"Creating new migration: {message}")
    
    # Change to backend directory
    os.chdir(backend_dir)
    
    # Clean the message for use in filename
    clean_message = re.sub(r'[^\w\s-]', '', message.lower())
    clean_message = re.sub(r'[-\s]+', '_', clean_message)
    
    try:
        # Run alembic revision with autogenerate
        result = subprocess.run(
            ["python", "-m", "alembic", "revision", "--autogenerate", "-m", clean_message],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("✅ Migration created successfully!")
            print(result.stdout)
            
            # Extract the revision file path from output
            match = re.search(r'Generating (.+\.py)', result.stdout)
            if match:
                migration_file = match.group(1)
                print(f"\n📄 Migration file: {migration_file}")
                print("\nNext steps:")
                print("1. Review the generated migration file")
                print("2. Make any necessary adjustments")
                print("3. Run 'python scripts/run_migrations.py' to apply the migration")
        else:
            print("❌ Failed to create migration!")
            print(result.stderr)
            sys.exit(1)
            
    except Exception as e:
        print(f"❌ Error creating migration: {e}")
        sys.exit(1)

def create_empty_migration(message):
    """Create an empty migration (no autogenerate)"""
    print(f"Creating empty migration: {message}")
    
    # Change to backend directory
    os.chdir(backend_dir)
    
    # Clean the message for use in filename
    clean_message = re.sub(r'[^\w\s-]', '', message.lower())
    clean_message = re.sub(r'[-\s]+', '_', clean_message)
    
    try:
        # Run alembic revision without autogenerate
        result = subprocess.run(
            ["python", "-m", "alembic", "revision", "-m", clean_message],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("✅ Empty migration created successfully!")
            print(result.stdout)
            
            # Extract the revision file path from output
            match = re.search(r'Generating (.+\.py)', result.stdout)
            if match:
                migration_file = match.group(1)
                print(f"\n📄 Migration file: {migration_file}")
                print("\nNext steps:")
                print("1. Add your upgrade() and downgrade() logic")
                print("2. Run 'python scripts/run_migrations.py' to apply the migration")
        else:
            print("❌ Failed to create migration!")
            print(result.stderr)
            sys.exit(1)
            
    except Exception as e:
        print(f"❌ Error creating migration: {e}")
        sys.exit(1)

if __name__ == "__main__":
    print("🚀 Network Management Platform - Migration Creator")
    print("=" * 60)
    
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python scripts/create_migration.py <message>        # Auto-generate migration")
        print("  python scripts/create_migration.py -e <message>     # Create empty migration")
        print("\nExample:")
        print("  python scripts/create_migration.py 'Add user preferences table'")
        print("  python scripts/create_migration.py -e 'Custom data migration'")
        sys.exit(1)
    
    if sys.argv[1] == "-e" and len(sys.argv) > 2:
        # Create empty migration
        message = " ".join(sys.argv[2:])
        create_empty_migration(message)
    else:
        # Create autogenerated migration
        message = " ".join(sys.argv[1:])
        create_migration(message)