[loggers]
keys=root,uvicorn,uvicorn.error,uvicorn.access,app

[handlers]
keys=console,file,error_file

[formatters]
keys=default,access

[logger_root]
level=INFO
handlers=console,file

[logger_uvicorn]
level=INFO
handlers=console,file
qualname=uvicorn
propagate=0

[logger_uvicorn.error]
level=ERROR
handlers=console,error_file
qualname=uvicorn.error
propagate=0

[logger_uvicorn.access]
level=INFO
handlers=console,file
qualname=uvicorn.access
propagate=0
formatter=access

[logger_app]
level=INFO
handlers=console,file
qualname=app
propagate=0

[handler_console]
class=StreamHandler
formatter=default
args=(sys.stdout,)

[handler_file]
class=handlers.RotatingFileHandler
formatter=default
args=('%(SNAP_DATA)s/logs/server.log', 'a', 10485760, 5)

[handler_error_file]
class=handlers.RotatingFileHandler
formatter=default
args=('%(SNAP_DATA)s/logs/error.log', 'a', 10485760, 5)

[formatter_default]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_access]
format=%(asctime)s - %(client_addr)s - "%(request_line)s" %(status_code)s
datefmt=%Y-%m-%d %H:%M:%S